---

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: make
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh release create "${{ github.ref }}" \
            --generate-notes \
            --verify-tag
  bump-index:
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://proxy.golang.org/github.com/mdb/funcy/@v/${{ github.ref }}.info"
